#TODO: Add differentiation between identification and resolution.
#TODO: Add explicit notifications when gap encountered
CONTROL_IDENTIFY_LEXICAL = True
CONTROL_RESOLVE_LEXICAL = True

CONTROL_IDENTIFY_NEGATION = True
CONTROL_RESOLVE_NEGATION = True

CONTROL_IDENTIFY_TARGET = True
CONTROL_RESOLVE_TARGET = True

CONTROL_IDENTIFY_CONTEXT = True

CONTROL_EXPORT_EACH_STEP_GRAPH = False

# INPUT FILE NAME/OUTPUT GRAPH NAME
CONST_INPUT_FILE_NAME = 'PVT'
# CONST_INPUT_FILE_NAME = 'VisualSearchNoMust'

